### ISSUE TITLE
Write performance regression

### ISSUE THREAD

**Issue by mdisibio** [segmentio/parquet-go#162]
Hi, I am seeing a regression in write performance ~0.5x after updating to the latest.  

```
-require github.com/segmentio/parquet-go v0.0.0-20220330180547-542d8f0815f1
+require github.com/segmentio/parquet-go v0.0.0-20220426180755-25a20d16fa7f
```

Attaching some cpu profiles for 3 runs:
  * cpu.old.out - Baseline, parquet.Writer only, ~15s
  * cpu.new.out - Latest, parquet.Writer only, ~37s
  * cpu.buffer.out - Latest, both parquet.Writer and Buffer, ~32s
[profiles.zip](https://github.com/segmentio/parquet-go/files/8584926/profiles.zip)

On initial scan it looks like more time spent in `parquet-go.clearValues` and `github.com/pierrec/lz4/v4/internal/lz4block.(*CompressorHC).CompressBlock`

**Comment by achille-roussel** [comment]
Thanks a lot of the report!

* The calls to `clearValues` do seem to take more time than they should

* The change on the LZ4 path may be due to a fix; parquet-go was mistakenly using the LZ4 stream format instead of the block format, which is required by the spec

I'm investigating, will get back to you if I find what's going on.

If you happen to have a dataset I can use or a Go benchmark to reproduce the regression, this would also be highly valuable.
