### ISSUE TITLE
Optimise Parquet ReadRow

### ISSUE THREAD

**Issue by annanay25** [segmentio/parquet-go#248]
At the moment, we perform one read per column to seek to a given row within a page. Below is a screenshot of the readrow operations for a schema with ~40 fields and ReadRow latency linearly increases with the number of fields. 

![image](https://user-images.githubusercontent.com/10982987/175005687-f769bfaf-a2ca-4b0a-b5cb-2c94a576d3da.png)

One way to improve this is to move markers for multiple columns concurrently -- lets use this issue to gather other ideas if any!

**Comment by zolstein** [comment]
@annanay25 Could you share any more information about how you generated that graph? Ideally a script / test-file, but failing that just a description of what you did and maybe some pseudocode? (In particular I'm curious how you set up the file to read from S3.) I have some thoughts on how the read performance might be improved based on some ideas / work from the [xitongsys library](https://github.com/xitongsys/parquet-go), but before I dump my brain and possibly hijack the issue I'd like to know what specific use-case you want to optimize.

**Comment by annanay25** [comment]
Hi @zolstein, thanks for looking into this. The visualisation is that of a trace exported from an instrumented application (https://github.com/grafana/tempo). `parquet.backendBlock.FindTraceByID` (the top line in the trace view) is a span generated from the [FindTraceByID operation](https://github.com/grafana/tempo/blob/150eeea11d11d8231d172c9fcebb8fbfbaaab35b/tempodb/encoding/vparquet/block_findtracebyid.go#L160) performed on our Query service responsible for fetching the parquet row corresponding to a given ID. The service scans through records in a parquet file present on object storage - first it sifts through the ID column to match the requested ID, and once found it retrieves the corresponding row to be displayed to the user. The resulting waterfall diagram in the above trace view shows the sequential nature of reads performed for a `ReadRow` operation. Since we have about 40-50 fields in the parquet schema present on the file, the latency for a single readrow operation goes up to 2.58s as shown.

> In particular I'm curious how you set up the file to read from S3

As `parquet.OpenFile()` takes an `io.ReaderAt` as an input, we implemented a wrapper around the s3/gcs/azure file handler that implements the `io.ReaderAt` interface. [Here](https://github.com/grafana/tempo/blob/150eeea11d11d8231d172c9fcebb8fbfbaaab35b/tempodb/encoding/vparquet/readers.go#L14-L34) is the code for reference.

**Comment by zolstein** [comment]
Right. I think to a large degree this can and should be fixed in the `io.ReaderAt` implementation, but we may also want to make some changes to the `parquet.Reader` for best effect.

For context, I think `io.ReaderAt` is a really sensible abstraction for the `parquet.Reader` to use. It provides pretty much exactly the API one would want for processing parquet files while giving the implementations a lot of flexibility.

Given this, when providing an implementation backed by an object-store you don't want individual `ReadAt` calls to correspond to individual API requests. Object stores will get better performance by, as much as possible, reading large contiguous chunks of data using a single request. (Reducing the number of API calls also reduces operational costs, since AWS et al. charge a cost per request.)

The [xitongsys library](https://github.com/xitongsys/parquet-go-source/blob/052319f3f36b6c7e9f375ce1f25a7020b77a8f5e/s3v2/s3.go#L149) uses a different model for reading, but it had a similar issue. I addressed by massively over-fetching requests and caching the response's `io.Reader` to use across `Read` calls, which could be used until the reader seeked to a different location in the file.

I tried porting this strategy over to this library, and it worked okay when reading the entire file at once, but didn't do great when reading smaller chunks of file, because the reader would seek between columns, throwing away sockets that it would eventually have continued reading from. However, caching multiple sockets according to their current offsets worked really well, at the cost of holding open some sockets that would never be read from again. Sample code [here](https://gist.github.com/zolstein/9f5a23c5bf54be56a780f38cae97100d). (I have not rigorously tested this. It seemed to work for reading, but might not handle edge cases correctly. Don't actually integrate this code anywhere.)

Using a map of offsets to readers is a little bit of a hack. Another alternative would be to make the column readers store separate `io.ReaderAt` that can track their current offsets independently. This would simplify the `io.ReaderAt` implementation a bit, and fix the issue of holding open sockets, at the cost of losing some socket reuse. (I.e. the first read of a new column chunk can't reuse the socket from the last read of an old column chunk.)

Since the implementations of `io.ReaderAt` around object-stores that work nicely with `parquet.Reader` are both non-trivial and pretty specific, we may want to provide something like what's in that gist in the library and let people plug in their own implementations of `ReadSource`.

Additionally, we may want to parallelize reading and processing columns. I've experimented with this a little bit, and I think it could significantly reduce latency, but I haven't yet managed to do this without making the reader slower. We may also want to make this configurable?

**Comment by achille-roussel** [comment]
Thanks for sharing all the details of your experiences and investigations @annanay25 @zolstein 

This issue is getting closer to the top of my priority list, so I will soon have cycles to review this thread thoroughly. I just wanted to send a quick update to let you know I appreciate the time investment!

**Comment by achille-roussel** [comment]
This PR I recently opened might provide part of the solution to this problem https://github.com/segmentio/parquet-go/pull/301

@annanay25 @zolstein if one of you have time to try it out, let me know if you have any feedback!
