### ISSUE TITLE
ARM64 assembler

### ISSUE THREAD

**Issue by vc42** [segmentio/parquet-go#259]
Hi, we are trying to use the parquet-go code on ARM64.  Is there a set of C/C++ files the AMD64 assembler code is based/derived on/from ?  If so, we'll try to produce ARM64 assembler files from them, in particular for the vectorized part.  Or you wrote all the assembler code by hand ?  Thanks !

**Comment by vc42** [comment]
Hi, I've attached a CPU profile obtained as a result of running on ARM64.  I've  re-implemented the validateByteArrays simple function in ARM64 asm, but real vectorized asm functions are a bit of a challenge.  If you could point to the functions affecting performance most, I'll try to dig deeper and re-implement those
[a.pprof.gz](https://github.com/segmentio/parquet-go/files/9085928/a.pprof.gz)
.

**Comment by achille-roussel** [comment]
Thanks!

Based on the profile you shared, I believe there are two main area of opportunities, none of which should require writing ARM assembly:

* about half of the time spent on parquet-go is done deconstructing Go values into parquet columns. This operation can be accelerated using `parquet.GenericWriter[T]` instead of `parquet.Writer`. The generic write having compile-time guarantees of the schema can optimize this process.

* While `parquet.Writer` allows a program to write rows one by one, `parquet.GenericWriter[T]` allows the application to pass an array of rows to write. When batching writes, a lot of the baseline cost can be amortized which should be very effective at yielding higher throughput. I wrote more details about it in https://github.com/segmentio/parquet-go/issues/149

Taking into account the profile you shared only, the most effective port of assembly code would be to implement gather loads in the [`sparse`](https://github.com/segmentio/parquet-go/tree/main/sparse) package, because those operations are used when deconstructing Go values into parquet columns.

In the profile you shared, I am not seeing stack traces on encoding code paths, which may be because your application wasn't performing any file encoding at the time I assume? (e.g. generating a large file and not yet reached the point where it would flush).

**Comment by vc42** [comment]
You wrote: "In the profile you shared, I am not seeing stack traces on encoding code paths, which may be because your application wasn't performing any file encoding at the time I assume?"

Hmm, that's bizarre because I definitely got an encoded file using this code, roughly:
`func main() {
	pf, err := os.Create("a.pprof")
	if err != nil {
		log.Fatal("could not create CPU profile: ", err)
	}
	defer pf.Close()
	if err = pprof.StartCPUProfile(pf); err != nil {
		log.Fatal("could not start CPU profile: ", err)
	}
	defer pprof.StopCPUProfile()

	//...
	buffer := new(bytes.Buffer)
	writerOptions := []parquet.WriterOption{
		parquet.Compression(&parquet.Gzip),
		parquet.PageBufferSize(64 * 1024),
	}
	fw := parquet.NewWriter(buffer, writerOptions...)

	for scanner.Scan() {
//...
		coreEvent, ok := rawEvent.(*log.CoreEvent)
		if !ok {
			return fmt.Errorf("failed to transform: expected: %T, but had: %T", coreEvent, rawEvent)
		}
		err = fw.Write(coreEvent)
		if err != nil {
			return fmt.Errorf("failed to write records: %w", err)
		}
		successCount++
	}
	err = fw.Close()
	if err != nil {
		return fmt.Errorf("failed to close writer: %w", err)
	}

}
`

Let me try your suggestions.

Thanks !

**Comment by vc42** [comment]
I've implemented your suggestion with GenericWrite and batching (10 rows for now).  It helped quite  bit.  On amd64, I am getting about 25% improvement (runtime 30s->22s) and on ARM64 about 40% (52s-> 31s).  

The CPU profiles are a little strange.  The same code spends only 14% of time on generic Write on amd64 vs 45% on arm64.  It does not look like the assembler functions have much impact on that unless I am missing something.  I've attached two profiles: a.pprof(amd64) and b.pprof(arm64) for your information.
[a.pprof.gz](https://github.com/segmentio/parquet-go/files/9094777/a.pprof.gz)
[b.pprof.gz](https://github.com/segmentio/parquet-go/files/9094778/b.pprof.gz)

**Comment by achille-roussel** [comment]
Following up here.

Would you be able to crank up the batch size to process 100 items at a time?

Otherwise, I'm curious if you are able to measure the throughput of processing, maybe int rows per second?

**Comment by achille-roussel** [comment]
Another thought that comes to mind, looking at the profiles you shared and the other issues you reported, I assume the parquet schema you are using has a lot of indirection in the form of pointer fields, slices of pointer types, etc...

Large number of such indirections can hurt performance because parquet-go cannot optimize write operations by working on column values since the values may be at unpredictable locations in memory. There are probably optimizations we could make to better handle these cases but it can gets very complex quickly.

If that's an option, have you considered changing the types to not be pointers, maybe use the zero-value as a marker indicating the values are missing, and add the `optional` struct tag.

For example, instead of have a structure like this:
```go
type FieldType struct {
  Name string
}
type Schema struct {
  Field *FieldType
}
```
use a structure like this one:
```go
type FieldType struct {
  Name string `parquet:",optional"`
}
type Schema struct {
  Field FieldType 
}
```

**Comment by achille-roussel** [comment]
I'm going to close this issue due to inactivity, but feel free to reopen if it requires further discussion.
