### ISSUE TITLE
How to make an optional map?

### ISSUE THREAD

**Issue by alanhe** [segmentio/parquet-go#280]
Take the sample below:
```go
type Spans struct {
  Attributes map[string]string
}

s := parquet.SchemaOf(new(RowType))
fmt.Println(s)
```

It prints:
```
message Spans {
  required group Attributes (MAP) {
    repeated group key_value {
      required binary key (STRING);
      required binary value (STRING);
    }
  }
}
```

However, I want the Attributes map to be optional:
```
message Spans {
  optional group Attributes (MAP) {
    repeated group key_value {
      required binary key (STRING);
      required binary value (STRING);
    }
  }
}
```

I try to add a tag, but it makes the value optional, not the map.
```
type Spans struct {
	Attributes map[string]string  `parquet:"Attributes,optional"`
}
```

Could you please teach me how to do it?

**Comment by Pryz** [comment]
The current schema doesn't support optional map unfortunately. We could introduce a `parquet-value` tag similar to `parquet-key` and change the `parquet` tag to configure the top level of the MAP.

Let me know if you are interested in implementing this change. Otherwise I will try to tackle that this week.
