### ISSUE TITLE
Occasional `bad use of unsafe.Pointer?` panics during GC

### ISSUE THREAD

**Issue by joe-elliott** [segmentio/parquet-go#309]
Rarely, Tempo compactors will panic with a message like the following:

```
runtime: marked free object in span 0x7fe7b258fb40, elemsize=64 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)
0xc0a06da000 free  unmarked
0xc0a06da040 free  unmarked
...
fatal error: found pointer to free object

goroutine 17 [running]:
runtime.throw({0x205b1e2?, 0xc0a06daf80?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc00008e5e8 sp=0xc00008e5b8 pc=0x43a0fd
runtime.(*mspan).reportZombies(0x7fe7b258fb40)
	/usr/local/go/src/runtime/mgcsweep.go:787 +0x2e5 fp=0xc00008e668 sp=0xc00008e5e8 pc=0x4285c5
runtime.(*sweepLocked).sweep(0x363a0e0?, 0x0)
	/usr/local/go/src/runtime/mgcsweep.go:611 +0x8d2 fp=0xc00008e740 sp=0xc00008e668 pc=0x427fd2
runtime.sweepone()
	/usr/local/go/src/runtime/mgcsweep.go:369 +0xf4 fp=0xc00008e790 sp=0xc00008e740 pc=0x427434
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:281 +0x105 fp=0xc00008e7c8 sp=0xc00008e790 pc=0x4271e5
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00008e7e0 sp=0xc00008e7c8 pc=0x41be06
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00008e7e8 sp=0xc00008e7e0 pc=0x46e641
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b
```

Complete dump:
[logs.txt](https://github.com/segmentio/parquet-go/files/9351165/logs.txt)

Vendored commit: `7efc157d28afda607e07e1f003e3c2c6922932df`
Go Version: 1.18

This actually used to happen more often and was reported [here](https://github.com/grafana/tempo/issues/1592). The latest parquet-go commit reduced the occurrences and changed where it occurred.

**Comment by vc42-2** [comment]
Yes, the problem does appear to be the same as ours:

Your stack fragments:
runtime: bad pointer in frame github.com/segmentio/parquet-go.writeRowsFuncOfStruct.func2 at 0xc0d9237200: 0x18

github.com/segmentio/parquet-go.writeRowsFuncOfRequired.func1({0xc05bf6fc00?, 0x35?, 0x35?}, {{0x18?, 0x0?, 0x0?}}, {0x4?, 0x1?, 0x3?})


Our stack:
runtime: bad pointer in frame github.com/segmentio/parquet-go.writeRowsFuncOfStruct.func2 at 0x401f087740: 0x20

github.com/segmentio/parquet-go.(*optionalColumnBuffer).writeValues(0x40070e4b60, {{0x20?, 0xc000?, 0x2000?}}, {0x0?, 0x60?, 0xbd?})

The 0x18 in your case and the 0x20 "address" in the first argument (rows sparse.Array -> {0x18?, 0x0?, 0x0?}) of the respective functions is the result of adding an offset to a nil pointer which is incorrect.  You can try one of the suggested fixes in my report.  We have not experienced any crashes yet since we applied the fix.

**Comment by joe-elliott** [comment]
I'm not seeing that function (`writeRowsFuncOfRequired`) in the linked stacktrace. Did you mean for this reply to go to #299? 

I almost commented on that issue with these details, but this felt distinct to me.

**Comment by vc42-2** [comment]
Oops, it was someone else's stack.  Ignore my comment.

**Comment by joe-elliott** [comment]
Following up on this. We continue to see this issue several times per day. It occurs to me though that we may be using the library incorrectly and I'd like some confirmation about whether or not this is true.

In our compactors we read 4 different parquet files and combine them into 1. In doing this we use `parquet.Reader` and `parquet.Writer` to read `parquet.Row`s and write them to the output block.

Is it ok to take a `parquet.Row` read from one `parquet.File` and write it to a different `parquet.File`?

**Comment by joe-elliott** [comment]
We ran some tests in our operational cluster and I can confirm that this issue does not exist on this commit:

https://github.com/segmentio/parquet-go/commit/d84ed320251d0c762d7188ca10154b2f9c66060e

and is present on this commit:

https://github.com/segmentio/parquet-go/commit/7efc157d28afda607e07e1f003e3c2c6922932df
