### ISSUE TITLE
Infinite loop in repeatedPageValues.ReadValues

### ISSUE THREAD

**Issue by asubiotto** [segmentio/parquet-go#327]
Run this test to reproduce:
```
func TestLoop(t *testing.T) {
	type testType struct {
		ListOfLists [][]int
	}
	instance := testType{ListOfLists: [][]int{{1, 3, 5}, nil, {2, 4, 6}}}
	buf := parquet.NewGenericBuffer[testType]()
	_, err := buf.Write([]testType{instance})
	require.NoError(t, err)

	rg := parquet.RowGroup(buf)
	chunks := rg.ColumnChunks()
	require.Equal(t, 1, len(chunks))
	pages := chunks[0].Pages()
	p, err := pages.ReadPage()
	require.NoError(t, err)

	vals := make([]parquet.Value, p.NumValues())
	_, _ = p.Values().ReadValues(vals)
}
```

It looks like the infinite loop is caused because this check always evaluates to false:
https://github.com/segmentio/parquet-go/blob/b03c0471ebb0eadd7fc54f41fccd58dafca80eee/page_values.go#L39

As soon as the `nil` is removed from the `testType` instantiation, the test completes successfully.

**Comment by abraithwaite** [comment]
Thinking out loud in this ticket, I'm confused by a few things.


It seems that we're not copying all the value containers we should because we break early due to the `maxDefinitionLevel` check:

```
(dlv) n
> github.com/segmentio/parquet-go.(*repeatedPageValues).ReadValues() ./page_values.go:73 (PC: 0x103320c64)
    68:         repetitionLevels := r.page.repetitionLevels
    69:         columnIndex := ^int16(r.page.Column())
    70:
    71:         for n < len(values) && r.offset < len(definitionLevels) {
    72:                 for n < len(values) && r.offset < len(definitionLevels) && definitionLevels[r.offset] != maxDefinitionLevel {
=>  73:                         values[n] = Value{
    74:                                 repetitionLevel: repetitionLevels[r.offset],
    75:                                 definitionLevel: definitionLevels[r.offset],
    76:                                 columnIndex:     columnIndex,
    77:                         }
    78:                         r.offset++
(dlv) p definitionLevels
[]uint8 len: 7, cap: 16384, [2,2,2,1,2,2,2]
(dlv) p maxDefinitionLevel
1
```

I believe 1 is the correct definitionLevel for the `nil` list embedded in the outer list, so I'm curious why `maxDefinitionLevel` is `1` (still investigating).

As a sanity check, I removed the `nil` from the list, and replaced it with another list in [this commit](https://github.com/segmentio/parquet-go/pull/331/commits/bd3a7713c3487e7127e269f787394c53a6a9d365).  To my surprise, it generates a new list without the infinite loop but the list is of a bunch of null `parquet.Values`:

```
go test -run 'Issue327' -v
=== RUN   TestIssue327
[<null> <null> <null> <null> <null> <null> <null> <null> <null>]
--- PASS: TestIssue327 (0.00s)
PASS
ok      github.com/segmentio/parquet-go 0.257s
```

We don't ever enter this block because `n == i`.

https://github.com/segmentio/parquet-go/blob/f812768dfa62ced67e9c8591183bf33e8eb35bff/page_values.go#L89-L95

We set `n := i` on line 82.

https://github.com/segmentio/parquet-go/blob/f812768dfa62ced67e9c8591183bf33e8eb35bff/page_values.go#L82

However, `n == len(values)` already (loop on line 72 created all the container values):

https://github.com/segmentio/parquet-go/blob/f812768dfa62ced67e9c8591183bf33e8eb35bff/page_values.go#L72

So we never drop into the block to actually read the values on lines 89-90, as mentioned above.

I don't believe this is the correct behavior, so more investigation is needed, but I'm going to need to understand better how this code should work before understanding how to fix the infinite loop issue.

**Comment by abraithwaite** [comment]
I found an alternate representation for nested lists that we use elsewhere in the codebase, which I pushed to #331 

I'm not sure if it's exactly the API we want, but it's not hitting the infinite loop and works with nils: https://github.com/segmentio/parquet-go/pull/331/commits/048aa05bd9d574f5c594f0e926adca3a2dd309fa

However, the `ReadValues` function still returns the nested lists as a flattened one, which I'm not sure is desirable from a user perspective.

**Comment by abraithwaite** [comment]
@asubiotto I just learned that we should tag list elements with `parquet:",list"` in order to properly handle list fields on Go structs.  Doing this works to prevent the infinite loop.  I'll be adding some code to prevent us from reaching the infinite loop without the tag as well.  In the meantime, you can annotate the struct as in this example to get the code functioning as expected:

https://github.com/segmentio/parquet-go/pull/331/commits/4ce543daf79f4585aa8c797a8524295cde25b2d6

**Comment by asubiotto** [comment]
Awesome, thanks! Yeah, I expect some error if it's not possible to process the struct + a suggestion to do it with the annotations.
