### ISSUE TITLE
How to return a Page to the pool?

### ISSUE THREAD

**Issue by mdisibio** [segmentio/parquet-go#370]
Hi, Grafana Tempo uses the low-level API for scanning columns, including ColumnChunk, PageReader, etc. There have been performance improvements to the library recently to introduce reference-counted buffers and I think there might be a gap where a `Page` (backed by `bufferedPage`) isn't returned to the pool, nor is there a way to do it manually.  It's possible that I missed the proper usage of these low-level structs, so this issue is both a possible finding and an ask for clarification.

Our [loop](https://github.com/grafana/tempo/blob/main/pkg/parquetquery/iters.go#L327) is basically:

```go
for _, rowGroup := range rowGroups {
    pages := rowGroup.ColumnChunks[n].Pages()
    defer pages.Close()

    for {
        page := pages.ReadPage()
        ...
```

It looks like new memory is allocated for every call to ReadPage(), and not reused from the internal pool, via a `bufferedPage` with new refs in [column.decodeDataPage](https://github.com/segmentio/parquet-go/blob/main/column.go#L675).   I didn't see where the page is [unref'd](https://github.com/segmentio/parquet-go/blob/main/buffer.go#L413) to return the buffers to the pool.

**Thoughts**

Should this be happening automatically, as the semantics of `ReadPage` mention that the given page is only valid until the next call?    Another possibility is to introduce `Page.Close()` which unrefs the buffers and allows downstream applications finer control over the lifetime.

**Comment by achille-roussel** [comment]
Hello @mdisibio, thanks for starting this discussion.

You are correct that at this time there is no mechanism to release pages. I initially did not want to expose external APIs without having a clear understanding of the use cases, so the feedback you provide is definitely valuable.

Something that I want to make sure is that we minimize the chances for an application to misuse the API. For example, if we introduce a `Close` method, it is possible for some pointers referencing memory within the page to become implicitly invalid (for BYTE_ARRAY or FIXED_LEN_BYTE_ARRAY pages for example). Such cases are fertile grounds for bugs, which makes it harder for users to use the library and adds maintenance time answering issues.

A single `Close` method might also not be useful in cases where the application needs to retain or share the page between multiple components. Internally, parquet-go has a reference counter for `bufferedPage`, it could make sense to expose an API to allow the application to manipulate the reference count. For example, the Apache Arrow library exposes Retain/Release methods on many objects as a manual memory management mechanism. While reference counting can be an effective solution to optimizing memory management, I don't believe that it is a common pattern for Go developers to use since we often more intuitively rely on the GC.

For these reasons, I believe that if we expose a way for the application to participate in granular memory management of the pages, we should make it an opt-in mechanism (e.g. the program is still correct if we let the GC reclaim memory). There are two approaches that I think we could take:

* Expose functions to change the reference count, using type assertion on the interface type to increment/decrement. Using these functions is optional and are only hints for the library:
```go
page, err := pages.ReadPage()
...
parquet.Release(page)
```

* Provide a function to support the use case you are referring to (which would also fix the ambiguous use of `defer` in your example). Then the contract is that none of the values read from the page must escape the scope of the closure used by the range function. Internally the library can close/release resources accordingly:
```go
parquet.RangePages(columnChunk, func(page parquet.Page) error {
  ...
})
```

Let me know what you think!

**Comment by mdisibio** [comment]
I would lean towards exposing Retain/Release methods as this provides the most amount of control for applications and doesn't introduce abstraction for error handling or concurrency.  We put Values in channels and if Retain/Release are exposed then there are two paths available: Clone the values and release the page immediately, or retain/release the backing page with the Value lifetimes.  The first case is essentially the same as the proposed callback, and benchmarks are promising (reduced cpu/mem despite the increased small allocs from Cloning many values).  Interested in testing the second  case as it seems to have both benefits: repool page, and no cloning.
