### ISSUE TITLE
Can I get Statistics DistinctCount from a Parquet column?

### ISSUE THREAD

**Issue by didip** [segmentio/parquet-go#384]
I am curious if distinct value is recorded in the parquet file itself.

**Comment by achille-roussel** [comment]
The parquet format defines a distinct count property on [row group and page statistics](https://github.com/apache/parquet-format/blob/43c891a4494f85e2fe0e56f4ef408bcc60e8da48/src/main/thrift/parquet.thrift#L217), but this value is very expensive to compute and hard to leverage:

- To compute an accurate count of distinct values for a row group, all values must be held in memory and indexed (e.g. using a hash table), which may require more memory than available to the application. If sacrificing accuracy is acceptable the parquet-go library could use a data structure like a HyperLogLog internally, but it still demands extra memory and CPU time to generate the approximate distinct count.

- Using the distinct count statistic is often difficult, an application cannot sum the distinct count of two row groups to determine the distinct count of a file for example. There are also alternative ways to access the distinct count; for columns with a dictionary, the distinct count can be determined by reading the dictionary and the application can merge dictionaries to get unique counts on the column across multiple row groups.

Overall, due to the use cases being unclear and the computation expensive, we have not yet implemented the generation of distinct count statistics in parquet-go.

Let me know if this answers your question!

**Comment by didip** [comment]
Thank you for explaining!

**Comment by achille-roussel** [comment]
> HLL structures can be merged, FWIW, if we do ever implement this.

This is true, we can use a HLL to generate the original distinct count, but we don't have any ways to record it in the parquet file. Ideally the parquet format specification would describe how to store a HLL for each column chunk, but this does not exist yet.

At this time, I believe that it would be preferable to implement this on the application side.
